### ISSUE TITLE
깃허브 Action을 사용한 배포자동화

### ISSUE THREAD

**Issue by csb9427** [TeamPiickle/server#67]
[comment]: <> (priority 와 task size를 뱃지로 정해주세요)

**📌 상세 설명**

[comment]: <> (이슈에 대한 설명을 적어주세요)
배포 자동화를 합니다.

**📝 체크리스트**

[comment]: <> (해야 할 일들을 상세히 나눠 적어주시면 좋아요)

- [ ] 배포에서 각자 구현한 기능이 다 작동하는 지 확인해주세요.

**Comment by kyY00n** [comment]
승빈짱 수고했엉
